apiVersion: apps/v1
kind: Deployment
metadata:
  name: webterminal-deployment
  labels:
    app: webterminal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webterminal
  template:
    metadata:
      labels:
        app: webterminal
    spec:
      containers:
      - name: webterminal
        image: s4msepiol/terminal_docker:1.1
        ports:
        - containerPort: 3000
      - name: sidecar
        image: bitnami/kubectl:latest  # Sidecar with kubectl
        #command: ["/bin/sh", "-c", "sleep infinity"]
---
apiVersion: v1
kind: Service
metadata:
  name: webterminal-service
spec:
  type: NodePort
  selector:
    app: webterminal
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 6060
      nodePort: 31000
